name: Print Software Versions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_software_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Display Data Processing Software Versions
        run: |
          echo "Checking Data Processing Software Versions..."
          python --version

  check_database_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Display Database Software Versions
        run: |
          echo "Checking Database Software Versions..."
          psql --version

